LCDDriver_NXP_Arduino: PCA8561 Class Reference
PCA8561 Class Reference
#include <LCDDriver.h>
Public Types
enum reg_num {
Software_reset , Device_ctrl , Display_ctrl_1 , Display_ctrl_2 ,
COM0_07_00 , COM0_15_08 , COM0_17_16 , COM1_07_00 ,
COM1_15_08 , COM1_17_16 , COM2_07_00 , COM2_15_08 ,
COM2_17_16 , COM3_07_00 , COM3_15_08 , COM3_17_16
}
Public Member Functions
PCA8561 (uint8_t i2c_address=(0x70 > > 1))
virtual ~PCA8561 ()
void begin (void)
void com_seg (int com, int seg, bool v)
void puts (const char *s, int dly=0)
void putchar (char c)
void clear (bool no_flush=false)
Static Public Attributes
static const int N_COM = 4
static const int N_SEG = 18
Private Member Functions
void flush (void)
void char2seg (int pos, int c)
Private Attributes
uint8_t bf [12]
char str_buffer [4]
int str_pos = 0
Static Private Attributes
static uint16_t char_pattern [61]
Detailed Description
LCDDriver operation library for Arduino
Author
Tedd OKANO
Released under the MIT license License PCA8561 class
PCA8561 class is a sample code for the PCA8561AHN-ARD It demonstrates LCD operation by
Definition at line 24 of file LCDDriver.h.
Member Enumeration Documentation
reg_num
enum PCA8561::reg_num
Enumerator
Software_reset
Device_ctrl
Display_ctrl_1
Display_ctrl_2
COM0_07_00
COM0_15_08
COM0_17_16
COM1_07_00
COM1_15_08
COM1_17_16
COM2_07_00
COM2_15_08
COM2_17_16
COM3_07_00
COM3_15_08
COM3_17_16
Definition at line 32 of file LCDDriver.h.
Constructor & Destructor Documentation
PCA8561()
PCA8561::PCA8561 (uint8_t i2c_address = (0x70 >> 1))
Create a PCA8561 instance with specified address
Parameters
i2c_address I2C-bus address (default: (0x70>>1))
Definition at line 5 of file LCDDriver.cpp.
~PCA8561()
PCA8561::~PCA8561 () virtual
Definition at line 15 of file LCDDriver.cpp.
Member Function Documentation
begin()
void PCA8561::begin (void)
Begin the device operation
This method turns-on the device
Definition at line 19 of file LCDDriver.cpp.
char2seg()
void PCA8561::char2seg (int pos, int c) private
Definition at line 83 of file LCDDriver.cpp.
Referenced by putchar().
clear()
void PCA8561::clear (bool no_flush = false)
Clear display
Parameters
no_flush no immidiate display clear (display will be cleared at next "putchar()" or "puts()" call)
Definition at line 72 of file LCDDriver.cpp.
Referenced by putchar().
com_seg()
void PCA8561::com_seg (int com, int seg, bool v)
Access to a segment
Parameters
com LCD backplane output select
seg LCD segment output select
v true for the segment ON
Definition at line 24 of file LCDDriver.cpp.
flush()
void PCA8561::flush (void) private
Definition at line 67 of file LCDDriver.cpp.
Referenced by clear(), and putchar().
putchar()
void PCA8561::putchar (char c)
Character output
Putting '
' or '\r' character to clear display in next "putchar()" or "puts()" call
Parameters
c A character to display
Definition at line 44 of file LCDDriver.cpp.
Referenced by puts().
puts()
void PCA8561::puts (const char * s, int dly = 0)
String output
Parameters
s A string to display
dly Option parameter for scroll effect each character appears with this delay [mili-second] (default: 0)
Definition at line 36 of file LCDDriver.cpp.
Member Data Documentation
bf
uint8_t PCA8561::bf[12] private
Definition at line 88 of file LCDDriver.h.
Referenced by char2seg(), clear(), flush(), and PCA8561().
char_pattern
uint16_t PCA8561::char_pattern static private
Initial value:
= {
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x4001,
    0x0000, 0x0000, 0x2AA8, 0x8282, 0x8282, 0x0280, 0x4000, 0x0820,
    0x1D74, 0x0440, 0x13C4, 0x16C4, 0x06D0, 0x1694, 0x1794, 0x0444,
    0x17D4, 0x16D4, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x07D4, 0x17B4, 0x1114, 0x9446, 0x1394, 0x0394, 0x1714,
    0x07D0, 0x9006, 0x1540, 0x21B0, 0x1110, 0x0578, 0x2558, 0x1554,
    0x03D4, 0x3554, 0x23D4, 0x1694, 0x8006, 0x1550, 0x0930, 0x2D50,
    0x2828, 0x8028, 0x1824, 0x0000, 0x2008,
}
Definition at line 91 of file LCDDriver.h.
Referenced by char2seg().
N_COM
const int PCA8561::N_COM = 4 static
The number of LCD backplane output
Definition at line 28 of file LCDDriver.h.
N_SEG
const int PCA8561::N_SEG = 18 static
The number of LCD segment output
Definition at line 31 of file LCDDriver.h.
str_buffer
char PCA8561::str_buffer[4] private
Definition at line 89 of file LCDDriver.h.
Referenced by putchar().
str_pos
int PCA8561::str_pos = 0 private
Definition at line 90 of file LCDDriver.h.
Referenced by clear(), PCA8561(), and putchar().
The documentation for this class was generated from the following files:
LCDDriver.h
LCDDriver.cpp